name: ffmpeg_cli
version: 0.3.0
description: Run FFMPEG CLI commands from Dart.
homepage: https://github.com/Flutter-Bounty-Hunters/ffmpeg_cli

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1
  collection: ^1.19.1

dev_dependencies:
  test: ^1.24.6
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
